<?php
/**
 * @file 
 * Defines the Twitpic module.
 */

/**
 * Implements hook_stream_wrappers().
 */
function twitpic_stream_wrappers() {
  return array(
    'twitpic' => array(
      'name' => 'Twitpic photos',
      'class' => 'TwitpicStreamWrapper',
      'description' => t('Photos from the Twitpic hosting service.'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,  
    ),
  );
}

/**
 * Implements hook_menu().
 */
function twitpic_menu() {
  $items = array();
  $items['twitpic/munge'] = array(
    'title' => 'Munge a Twitpic image',
    'descripttion' => t('Displays a Twitpic image, munged in various ways 
                        (cropped, rotated, etc.'),
    'page callback' => 'twitpic_image_munge',
    'access arguments' => array('access_content'),
    'type' => MENU_CALLBACK,
  );
  $items['twitpic/view'] = array(
    'title' => 'View a Twitpic image',
    'description' => t('Displays a Twitpic image, given an ID'),
    'page callback' => 'twitpic_image_view',
    'access arguments' => array('access_content'),
    'type' => MENU_CALLBACK,
  );
  $items['twitpic/style'] = array(
    'title' => 'Munge a Twitpic image according to an image style',
    'description' => t('Displays a Twitpic image, munged by an image style'),
    'page callback' => 'twitpic_image_style',
    'access arguments' => array('access_content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Menu callback (/twitpic/view/%).
 * 
 * View an image from Twitpic.
 * 
 * Note this function does not return anything and does not display the image
 * in the context of your Drupal site. It simply displays the image itself and
 * nothing else. This is just used as a demonstration of how file_transfer() and
 * stream wrappers work.
 * 
 * @param $id
 *   The image id extracted from the URL.
 * @param $size
 *   The image size. This can either be 'thumb' or 'mini'.
 */   
function twitpic_image_view($id, $size) {
  file_transfer('twitpic://' . $id . '/' . $size, array('content-type' => 'image/jpeg'));
}

/**
 * Menu callback (/twitpic/munge/%/%).
 * 
 * Munge an image from Twitpic applying a resize, crop or rotate to it.
 * 
 * Note this function does not return anything and does not display the image
 * in the context of your Drupal site. It simply displays the image itself and
 * nothing else. This is just used as a demonstration of how file_transfer(), 
 * image api functions, and stream wrappers work.
 * 
 * @param $id
 *   The image's id extracted from the URL.
 * @param $operation
 *   An operation to perform on the image, can be rotate, scale or desaturate.
 */
function twitpic_image_munge($id, $operation = 'rotate') {
  // If we get a disallowed option just return.
  $operations = array('rotate', 'scale', 'desaturate');
  if (!in_array($operation, $operations)) {
    return;
  }
  
  $twitpic_uri = 'twitpic://' . $id . '/thumb';
  $local_uri = 'public://' . $id . '.jpg';
  $twitpic_image = file_get_contents($twitpic_uri);
  if (!$twitpic_image) {
    return;
  }
  $local_path = file_unmanaged_save_data($twitpic_image, $local_uri, FILE_EXISTS_REPLACE);
  // Get a Drupal image object that we can pass to the image style functions.
  $local_image = image_load($local_path);

  switch ($operation) {
    case 'scale':
      image_scale($local_image, NULL, 50, FALSE);
      break;
    case 'desaturate':
      image_desaturate($local_image);
      break;
    case 'rotate':
      image_rotate($local_image, 45, 0x7D26CD);
      break;
  }
  
  $local_uri = drupal_tempnam('public://', $id);
  image_save($local_image, $local_uri);
  
  return theme('image', array('path' => $local_uri));
}  















