<?php

define('DEFAULT_URL', 'http://randersbib.dk');
define('PATH', drupal_get_path('module', 'embed_facebook'));

/**
 * @file 
 * This module allows site administrators to embed various facebook-plugins
 * on the website.
 */

/**
 * Implements hook_page_build().
 * 
 * Adds the facebook sdk loader to the page render array. Because it is
 * recommended to place the loader after the opening body tag, the region 
 * page-top is used.
 */
function embed_facebook_page_build(&$page) {
  $page['page_top']['facebook_root_div'] = array(
    '#prefix' => '<div id="fb-root">',
    '#suffix' => '</div>',  
  );
  $page['page_top']['facebook_sdk_loader'] = array(
    '#prefix' => '<script>',
    '#suffix' => '</script>',
    '#markup' => file_get_contents(PATH . '/embed-facebook-sdk-loader.js'), 
  );
}

/**
 * Implements hook_preprocess_html().
 * 
 * Adds a general stylesheet to evey page with rules which apply to every plugin 
 * container div.
 * 
 * Adds a general javascript file to every page.
 */
function embed_facebook_preprocess_page(&$variables) {
  $css_options = array(
    'group' => CSS_DEFAULT,
    'every_page' => TRUE,  
  );
  drupal_add_css(PATH . '/embed-facebook.css', $css_options);
  $js_options = array(
    'group' => JS_DEFAULT,
    'every_page' => TRUE,
  );
  drupal_add_js(PATH . '/embed-facebook.js', $js_options);
}

/**
 * Implements hook_block_info().
 * 
 * Declares the various blocks provided in this module.
 */
function embed_facebook_block_info() {
  $blocks = array();
  $blocks['like_button'] = array(
    'info' => t('Facebook like button'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function embed_facebook_block_view($delta) {
  $block = array(
    'subject' => '',
    'content' => '',  
  );
  if ($delta == 'like_button') {
    $block['subject'] = t('Facebook');
    $block['content']['like_button'] = array(
      '#theme' => 'embed_facebook__like',
      '#type' => 'like',  
      '#layout' => 'box_count',
      '#width' => '100',  
    );
    $css_options = array(
      'group' => CSS_DEFAULT,
    );
    $block['content']['#attached']['css'][PATH . '/embed-facebook-like.css'] = $css_options;
  }
  return $block;
}

/**
 * Implements hook_theme().
 * 
 * Declares a theme hook for each facebook plugin this module supports
 */
function embed_facebook_theme($existing, $type, $theme, $path) {
  return array(
    'embed_facebook' => array(
      'variables' => array(
        'type' => 'like',  
        'url' => DEFAULT_URL,
        'send' => TRUE,  
        'colorscheme' => 'light',
        'action' => 'like',
        'layout' => 'standard',
        'width' => '450',
        'faces' => TRUE,  
      ),
      'template' => 'embed-facebook',  
    ),
  );
}

/**
 * Preprocess the variables for the embed_facebook_like_button theme hook.
 */
function template_preprocess_embed_facebook(&$variables) {
  $variables['attributes_array'] += array(
    'data-href' => $variables['url'],
    'data-colorscheme' => $variables['colorscheme'],  
  );
  // Setup variables specific to the like button plugin
  if ($variables['type'] == 'like') {
    $variables['attributes_array'] += array(
      'data-send' => $variables['send'],
      'data-action' => $variables['action'],
      'data-layout' => $variables['layout'],
      'data-width' => $variables['width'],  
    );
    $variables['classes_array'][] = 'fb-like';
  }
}


