<?php

define('DEFAULT_URL', 'http://randersbib.dk');

/**
 * @file 
 * This module allows site administrators to embed various facebook-plugins
 * on the website.
 */

/**
 * Implements hook_page_build().
 * 
 * Adds the facebook sdk loader to the page render array. Because it is
 * recommended to place the loader after the opening body tag, the region 
 * page-top is used.
 */
function embed_facebook_page_build(&$page) {
  $page['page_top']['facebook_root_div'] = array(
    '#prefix' => '<div id="fb-root">',
    '#suffix' => '</div>',  
  );
  $fb_loader_script = <<<END
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/da_DK/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, "script", "facebook-jssdk"));
END;
  $page['page_top']['facebook_sdk_loader'] = array(
    '#prefix' => '<script>',
    '#suffix' => '</script>',
    '#markup' => $fb_loader_script, 
  );
}

/**
 * Implements hook_block_info().
 * 
 * Declares the various blocks provided in this module.
 */
function embed_facebook_block_info() {
  $blocks = array();
  $blocks['like_button'] = array(
    'info' => t('Facebook like button'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function embed_facebook_block_view($delta) {
  $block = array(
    'subject' => '',
    'content' => '',  
  );
  if ($delta == 'like_button') {
    $block['subject'] = t('Facebook');
    $block['content']['like_button'] = array(
      '#theme' => 'embed_facebook__like',
      '#type' => 'like',  
      '#layout' => 'box_count',
      '#width' => '100',  
    );
    $css_options = array(
      'group' => CSS_DEFAULT,
      'preprocess' => false,
    );
    $css_path = drupal_get_path('module', 'embed_facebook') . '/embed-facebook.css';
    $block['content']['#attached']['css'] = array($css_path => $css_options);
  }
  return $block;
}

/**
 * Implements hook_theme().
 * 
 * Declares a theme hook for each facebook plugin this module supports
 */
function embed_facebook_theme($existing, $type, $theme, $path) {
  return array(
    'embed_facebook' => array(
      'variables' => array(
        'type' => 'like',  
        'url' => DEFAULT_URL,
        'send' => TRUE,  
        'colorscheme' => 'light',
        'action' => 'like',
        'layout' => 'standard',
        'width' => '450',
        'faces' => TRUE,  
      ),
      'template' => 'embed-facebook',  
    ),
  );
}

/**
 * Preprocess the variables for the embed_facebook_like_button theme hook.
 */
function template_preprocess_embed_facebook(&$variables) {
  $variables['attributes_array'] += array(
    'data-href' => $variables['url'],
    'data-colorscheme' => $variables['colorscheme'],  
  );
  // Setup variables specific to the like button plugin
  if ($variables['type'] == 'like') {
    $variables['attributes_array'] += array(
      'data-send' => $variables['send'],
      'data-action' => $variables['action'],
      'data-layout' => $variables['layout'],
      'data-width' => $variables['width'],  
    );
    $variables['classes_array'][] = 'fb-like';
  }
}
