<?php

/**
 * @file
 * 
 * Provides an example of creation of a custom entity using the entity module.
 */

/**
 * Implements hook_entity_info().
 */
function postit_entity_info() {
  $entity_info['postit'] = array(
    'label' => t('Postit Note'),
    'controller class' => 'PostItController',
    'base table' => 'postit',
    'uri callback' => 'postit_uri',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'pid',
    ),
    'static cache' => TRUE,
    'bundles' => array(
      'postit' => array(
        'label' => 'PostIt',
        'admin' => array(
          'path' => 'admin/structure/postit/manage',
          'access arguments' => array('administer postits'),
        ),
      ),
    ),
    'view modes' => array(
      'full' => array(
        'label' => t('Full Postit'),
        'custom settings' => FALSE,
      ),
    ),
  );
  return $entity_info;
}
 
/**
 * Entity uri callback funtion for the Postit entity.
 */
function postit_uri($postit) {
   return array(
     'path' => 'postit/' . $postit->id,
   );
}
 
/**
 * Load a Postit entity from the database.
 */
function postit_load($pid = NULL, $reset = FALSE) {
  $pids = (isset($pid) ? array($pid) : array());
  $postit = postit_load_multiple($pids, $reset);
  return $postit ? reset($postit) : FALSE;
}
 
/**
 * Load Postit entities from the database.
 */
function postit_load_multiple($pids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('postit', $pids, $conditions, $reset);
}

/**
 * Save a Postit note in the database.
 */
function postit_save($postit) {
  return entity_get_controller('postit')->save($postit);
}

/**
 * Implements hook_menu().
 */
function postit_menu() {
  $items['admin/structure/postit/manage'] = array(
    'title' => 'Postit Admin',
    'description' => t('Manage Postit structure.'),
    'page callback' => 'postit_info',
    'access arguments' => array('administer postits'),
  );
  $items['postit/%postit'] = array(
    'title callback' => 'postit_page_title',
    'title arguments' => array(1),
    'page callback' => 'postit_page_view',
    'page arguments' => array(1),
    'access arguments' => array('view postits'),
    'type' => MENU_CALLBACK,
  );
  $items['postit/add'] = array(
    'title' => 'Add Postit!',
    'page callback' => 'postit_add',
    'access arguments' => array('create postit'),
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function postit_permission() {
  return array(
    'administer postits' => array(
      'title' => t('Administer Postits'),
      'restrict access' => TRUE,  
    ),
    'view postits' => array(
      'title' => t('View Postits'),
    ),
    'create postit' => array(
      'title' => t('Create Postit'),
    ),
  );
}

/**
 * Page callback
 */
function postit_info() {
  return t('Welcome to the administration page for your Postits!.');
}

/**
 * Page Title callback
 */
function postit_page_title($postit) {
  return $postit->pid;
}

/**
 * Page callback
 */
function postit_page_view($postit, $view_mode = 'full') {
  $postit->content = array();
  // Build field content.
  field_attach_prepare_view('postit', array($postit->pid => $postit), $view_mode);
  entity_prepare_view('postit', array($postit->pid => $postit));
  $postit->content += field_attach_view('postit', $postit, $view_mode);
  $postit->content['note'] = array(
    '#prefix' => '<p>',
    '#suffix' => '</p>',
    '#markup' => $postit->note,
  );
  return $postit->content;
}

/**
 * Page callback
 */
function postit_add() {
  $postit = (object) array(
    'pid' => '',
    'type' => 'postit',
    'note' => '',
  );
  return drupal_get_form('postit_add_form', $postit);
}

/**
 * Form builder for adding new Postits.
 */
function postit_add_form($form, &$form_state, $postit) {
  $form['note'] = array(
    '#type' => 'textfield',
    '#title' => t('Note'),
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  field_attach_form('postit', $postit, $form, $form_state);
  return $form;
}

/**
 * Validate callback for the postit_add_form.
 */
function postit_add_form_validate($form, &$form_state) {
  $postit_submission = (object)$form_state['values'];
  field_attach_form_validate('postit', $postit_submission, $form, $form_state);
}

/**
 * Submit callback for the postit_add_form.
 */
function postit_add_form_submit($form, &$form_state) {
  $postit_submission = (object)$form_state['values'];
  field_attach_submit('postit', $postit_submission, $form, $form_state);
  $postit = postit_save($postit_submission);
  $form_state['redirect'] = "postit/$postit->pid";
}

/**
 * Implements hook_field_extra_fields().
 */
function postit_field_extra_fields() {
  $return = array();
  $return['postit']['postit'] = array(
    'form' => array(
      'note' => array(
        'label' => t('Note'),
        'description' => t('Postit Note'),
        'weight' => 0,
      ),
    ),
    'display' => array(
      'note' => array(
        'label' => t('Note'),
        'description' => t('Postit Note'),
        'weight' => 0,
      ),
    ),    
  );
  return $return;
}

 
 
 
 
 
 
 
 

 
 
 
 
 
 
 
 
 
 
 